### ISSUE TITLE
Recoverable Error

### ISSUE THREAD

**Issue by vvzar** [ItalianDevs4PM/TNTRun#3]
"Argument 1 passed to TNTRun\commands\SubCmd::__construct() must be an instance of TNTRun\Main, instance of TNTRun\commands\TNTRunCommand given, called in phar:///mcpe/fwars-mpe/plugins/TNTRun_v1.0.0.phar/src/TNTRun/commands/TNTRunCommand.php on line 30 and defined" (E_RECOVERABLE_ERROR) in "/TNTRun_v1.0.0.phar/src/TNTRun/commands/SubCmd" at line 12

**Comment by legoboy0215** [comment]
This is a error, but BIM that this is WIP.
$BIM = 'bear in mind';

**Comment by luca28pet** [comment]
This plugin is not finished as said in #1
It will be released soon on pocketmine forums

**Comment by legoboy0215** [comment]
@uca28pet, lock this too...
