### ISSUE TITLE
Problem with GameSender.php

### ISSUE THREAD

**Issue by KevinLong021** [ItalianDevs4PM/TNTRun#6]
When I load the plugin this is spammed in the console.
![screenshot_2016-12-04-11-56-27](https://cloud.githubusercontent.com/assets/23292604/20867728/f1667b1c-ba18-11e6-990f-83681cf557ce.png)

**Comment by NyaomiDEV** [comment]
@Mrfanman345 This happens when you don't praise the Dux.
Dux mea Lux. Hail Mussolini!

**Comment by NyaomiDEV** [comment]
Dude, this plugin is discontinued and far from being used in production. What did you expect?

Cheers. ;D
